urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'shekho.session.views.index'),
    url(r'^sessions/submit', 'shekho.session.views.submit'),
    url(r'^sessions/browse', 'shekho.session.views.browse'),
    url(r'^sessions/dashboard', 'shekho.session.views.dashboard'),
    url(r'^sessions/view/(?P<session_id>\d+)/$', 'shekho.session.views.details'),
    url(r'^sessions/(?P<session_id>\d+)/signup$', 'shekho.session.views.session_signup'),
    url(r'^sessions/(?P<session_id>\d+)/confirm$', 'shekho.session.views.session_confirm'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'shekho.session.views.user_logout'),
    url(r'^accounts/register/$', 'shekho.session.views.register'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

session/models.py
from django.db import models
from django.contrib.auth.models import User

SESSION_STATUS = (('confirmed', 'Confirmed'),
                    ('unconfirmed', 'Unconfirmed'),
                    ('cancelled', 'Cancelled'))

# Need type ?
class Session(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    facilitator = models.ForeignKey(User, related_name="facilitator")
    status = models.CharField(max_length=20, choices = SESSION_STATUS,\
        default='unconfirmed')
    #location = models.TextField(blank=True)
    #time = models.DateTimeField(blank=True)
    type = models.CharField(max_length=100)
    duration = models.CharField(max_length = 50)
    attendees = models.ManyToManyField(User, null=True, blank=True,\
        related_name="attendees")

    def __unicode__(self):
    	return self.title

    def confirmed(self):
      if self.status == "confirmed":
        return True
      else:
        return False

session/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

import shekho.session.models

class SessionForm(ModelForm):
    class Meta:
        model = shekho.session.models.Session


class RegistrationForm(UserCreationForm):
	username = forms.CharField(max_length=30)
	first_name = forms.CharField(max_length=30)
	last_name = forms.CharField(max_length=30)
	email = forms.EmailField(max_length=75)
	
	class Meta:
		model = User
		fields = ("username", "first_name", "last_name", "email",)
	
	def save(self, commit=True):
		user = super(RegistrationForm, self).save(commit=False)
		user.username = self.cleaned_data["username"]
		user.first_name = self.cleaned_data["first_name"]
		user.last_name = self.cleaned_data["last_name"]
		user.email = self.cleaned_data["email"]
		if commit:
			user.save()
		return user

session/views.py
import simplejson

from django.template import RequestContext, loader
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.context_processors import csrf
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from shekho.session.models import SESSION_STATUS, Session
from shekho.session.forms import SessionForm, RegistrationForm

def index(request):
    t = loader.get_template('session/index.html')

    c = RequestContext(request, {
    })

    return HttpResponse(t.render(c))

def browse(request):
    sessions = Session.objects.all()
    return render_to_response('session/browse.html', \
        {'sessions' : sessions}, \
        context_instance=RequestContext(request))

def details(request, session_id):
    session =  get_object_or_404(Session, pk=session_id)
    if session.status == 'confirmed':
    	confirmed = True
    else:
    	confirmed = False
    
    signed_up = False
    if request.user.is_authenticated():
    	if request.user in session.attendees.all():
    		signed_up = True
    	
    t = loader.get_template('session/details.html')
    c = RequestContext(request, {
        'session' : session,
        'confirmed' : confirmed,
        'signed_up' : signed_up,
    })

    return HttpResponse(t.render(c))

@login_required
def dashboard(request):
	sessions = Session.objects.filter(facilitator=request.user)
	
	return render_to_response('session/dashboard.html', \
		{'sessions' : sessions}, \
		context_instance=RequestContext(request))
	
	

@login_required
def submit(request):
    t = loader.get_template('session/submit.html')

    submission_success = False

    if request.method == 'POST':
        form = SessionForm(request.POST)
        if form.is_valid():
            form.save()
            submission_success = True
    else:
        form = SessionForm()

    c = RequestContext(request, {
        'form': form, 'success' : submission_success})

    c.update(csrf(request))
    return HttpResponse(t.render(c))

@login_required
def session_confirm(request, session_id):
	try:
		session = Session.objects.get(pk=session_id)
	except Session.DoesNotExist:
		return HttpResponse(simplejson.dumps({'result' : False}), 'text/javascript')
		
	if request.user == session.facilitator:
		session.status = 'confirmed'
		session.save()
		return HttpResponse(simplejson.dumps({'result' : True}), 'text/javascript')
	else:
		return HttpResponse(simplejson.dumps({'result' : False}), 'text/javascript')
    
@login_required
def session_signup(request, session_id):
    try:
        session = Session.objects.get(pk=session_id)
    except Session.DoesNotExist:
        return HttpResponse(simplejson.dumps({'result' : False}), 'text/javascript')

    session.attendees.add(request.user)
    session.save()

    return HttpResponse(simplejson.dumps({'result' : True}), 'text/javascript')

# This should ideally go somewhere else
def register(request):
	if request.user.is_authenticated(): # Disallow access to logged in users
		return HttpResponseRedirect('/')

	t = loader.get_template('registration/register.html')
    
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			new_user = form.save()
			new_user = \
				authenticate(username=request.POST['username'], \
				password=request.POST['password1'])
			login(request, new_user)
			return HttpResponseRedirect('/')
		else:
			c = RequestContext(request, {'form': form})
			c.update(csrf(request))
			return HttpResponse(t.render(c))			
			
	form = RegistrationForm()

	c = RequestContext(request, {'form': form})
	c.update(csrf(request))

	return HttpResponse(t.render(c))
	
def user_logout(request):
	logout(request)
	return HttpResponseRedirect('/')

templates/session/base.html
<html lang="en">
<head>
   <title>Festival of Learning - {%block pagetitle %}{% endblock %}</title>
   <link rel="stylesheet" href="/static/bootstrap.css">
   <style type="text/css">
      body {
        padding-top: 60px;
        background-color: #fff;
        line-height: 1.5385em;
      }
      .alert-message.block-message {
          background-color: white;
      }
      input, select, .uneditable-input {
          height: 28px;
      }
    </style>

    {% block style %}{% endblock %}

    <script type="text/javascript" src="/static/js/jquery-1.6.4.min.js"></script>
    {% block scripts %}{% endblock %}
    <script src="/static/js/bootstrap-dropdown.js"></script>

</head>
<body>
    <div class="topbar">
      <div class="topbar-inner">
        <div class="container">
          <a class="brand" href="/">Festival of Learning</a>
          <ul class="nav">
          {% block navbar %}{% endblock %}
          </ul>
          <ul class="nav secondary-nav">
            {% if user.is_authenticated %}
            <li class="dropdown" data-dropdown="dropdown">
            <a href="#" class="dropdown-toggle">{{ user.username }}</a>
            <ul class="dropdown-menu">
            <li><a href="/sessions/dashboard">Dashboard</a></li>
            {% if user.is_staff %}
            <li><a href="/admin">Admin Dashboard</a></li>
            {% endif %}
            <li>
            <li class="divider"></li>
            <li><a href="/accounts/logout">Logout</a></li>
            </ul>
            </li>
            {% else %}
            <li><a href="/accounts/login">Sign in</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  <div class="container">
  <div class="row">
   {% block banner %}{% endblock %}
    <div class="span16">
        {% block primary %}{% endblock %}
    </div>
   </div>
   <footer>
   <a href="http://web.mit.edu">MIT</a> | <a href="http://media.mit.edu">Media Lab</a> |  <a href="http://cms.mit.edu">CMS</a> | <a href="http://act.mit.edu">ACT</a>
  </footer>
  </div>
</body>
</html>

templates/session/browse.html
{% extends 'session/base.html' %}

{% block pagetitle %}Browse Session Ideas{% endblock %}

{% block scripts %}
<script>
$(function() {
   $("tr").click(function(){
      window.location = $(this).data("url");

   });
});
</script>
{% endblock %}

{% block navbar %}
            <li><a href="/">Home</a></li>
            <li><a href="/sessions/submit">Submit Session</a></li>
            <li class="active"><a href="/sessions/browse">Browse Sessions</a></li>
            <li><a href="http://festival-of-learning.media.mit.edu/">About</a></li>
{% endblock %}


{% block primary %}
{% autoescape off %}
<div class="row">
 <div class="span16">
  <h4>All session ideas</h4>
  <table class="condensed-table bordered-table zebra-striped">
    <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Status</th>
          </tr>
    </thead>
    <tbody>
    {% for session in sessions %}
      <tr data-url="/sessions/view/{{ session.id }}" style="cursor:pointer;">
        <td>{{ session.title }}</td> 
        <td>{{ session.description }}</td>
        <td>{% if session.confirmed %}<span class="label success">Confirmed</span>
            {% else %} &nbsp; {% endif %}</td>

      </tr>
    {% endfor %}
    </tbody>
  </table>

 </div>
</div>
{% endautoescape %}

{% endblock %}

templates/session/dashboard.html
{% extends 'session/base.html' %}

{% block pagetitle %}Dashboard{% endblock %}

{% block scripts %}
    <script src="/static/js/bootstrap-twipsy.js"></script>
    <script src="/static/js/bootstrap-popover.js"></script>
    <script src="/static/js/bootstrap-modal.js"></script>
    <script src="/static/js/bootstrap-alerts.js"></script>
            <script>
            $(function () {
              $("a[rel=twipsy]").twipsy({
                live: true
              })
            })
          </script>
          <script>
function confirm(session_id) {
    $.getJSON('/sessions/'+session_id+'/confirm', function(data) {
        //TODO: Check for errors
        console.log(data);
        $("#confirm-"+session_id).attr('onClick', '');
        $("#confirm-"+session_id).addClass('disabled');
        $("#confirm-"+session_id).html('Confirmed!');
    })
}
</script>
{% endblock %}

{% block navbar %}
            <li><a href="/">Home</a></li>
            <li><a href="/sessions/submit">Submit Session</a></li>
            <li><a href="/sessions/browse">Browse Sessions</a></li>
            <li><a href="http://festival-of-learning.media.mit.edu/">About</a></li>
{% endblock %}

{% block primary %}

<div class="row">
 <div class="span16">
  <h4>Your session ideas</h4>
  <table class="condensed-table bordered-table zebra-striped">
    <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th></th>
          </tr>
    </thead>
    <tbody>
    {% for session in sessions %}
      <tr data-url="/sessions/view/{{ session.id }}" style="cursor:pointer;">
        <td>{{ session.title }}</td>
        {% autoescape off %}
        <td>{{ session.description }}</td>
        {% endautoescape %}
        <td>
        <button data-controls-modal="modal-for-session-{{session.id}}" data-backdrop="true"  data-keyboard="true" class="btn small" >Signups</button>
        
        <br><br>
        {% if session.status == "confirmed" %}
        <a id="confirm-{{session.id}}" href="#" class="btn small disabled">Confirmed!</a>
        {%else%}
        <a id="confirm-{{session.id}}" href="#" class="btn small" onClick="confirm({{session.id}});">Confirm</a>
        {%endif%}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

 </div>
</div>

{% for session in sessions %}
        	<div id="modal-for-session-{{session.id}}" class="modal hide fade in">
            <div class="modal-header">
              <a href="#" class="close">×</a>
              <h3>Sign ups for {{session.title}}</h3>
            </div>
            <div class="modal-body">
              <ul>
              	{% for attendee in session.attendees.all %}
				{{attendee.first_name}} {{attendee.last_name}} &lt;{{attendee.email}}&gt;,<br/>
				{%endfor%}
              </ul>
            </div>
            <div class="modal-footer">
              Please do not share these email addresses.
            </div>
        </div>
{% endfor %}

{% endblock %}

templates/session/details.html
{% extends 'session/base.html' %}

{% block pagetitle %}Home{% endblock %}

{% block scripts %}
{% if user.is_authenticated %}
<script>
function signup() {
    $.getJSON('/sessions/{{session.id}}/signup', function(data) {
        //TODO: Check for errors
        console.log(data);
        $("#signup").attr('onClick', '');
        $("#signup").addClass('disabled');
        $("#signup").html('Signed-up!');
        $("#attendeelist").append('<li>{{user.first_name}} {{user.last_name}}</li>')
        
    })
}
</script>
{% endif %}
{% endblock %}

{% block navbar %}
            <li><a href="/">Home</a></li>
            <li><a href="/sessions/submit">Submit Session</a></li>
            <li><a href="/sessions/browse">Browse Sessions</a></li>
            <li><a href="http://festival-of-learning.media.mit.edu/">About</a></li>
{% endblock %}

{% block banner %}
{% endblock %}

{% block primary %}
<div class="row">
<div class="span16">
  <h3>{{ session.title }}</h3>
  {% if confirmed %}
  <span class="label success">Confirmed</span>
  {% endif %}
  <h6>By {{ session.facilitator.first_name }} {{ session.facilitator.last_name }}</h6>
<p><strong>Duration:</strong> {{session.duration}}</p>
<p><strong>Type:</strong> {{session.type}}</p>
{% autoescape off %}
<p>  {{ session.description }}<p>
{% endautoescape %}
  <br><br>
  {% if user.is_authenticated %}
  {% if signed_up %}
  <a id="signup" href="#" class="btn small disabled">Signed-up!</a>
  {% else %}
  <a id="signup" href="#" class="btn small" onClick="signup();">Sign me up!</a>
  {% endif %}
  {% else %}
  <a id="signup" href="/accounts/login" class="btn small">Log in to sign up.</a>  
  {% endif %}
</div>
</div>

<div class="row">
 <div class="span16">
 <br>
 <div class="well">
 <h5>Attendees</h5>
  <ul id="attendeelist">
	{% for attendee in session.attendees.all %}
	<li>{{attendee.first_name}} {{attendee.last_name}}</li>
	{%endfor%}
  </ul>
 </div> 
 </div>
</div>

 <div class="row">
 <div class="span16">
 <div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = 'festivaloflearning'; 
    var disqus_identifier = 'test{{session.id}}';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
 
<hr>
{% endblock %}

templates/session/index.html
{% extends 'session/base.html' %}

{% block pagetitle %}Home{% endblock %}

{% block navbar %}
            <li class="active"><a href="/">Home</a></li>
            <li><a href="/sessions/submit">Submit Session</a></li>
            <li><a href="/sessions/browse">Browse Sessions</a></li>
            <li><a href="http://festival-of-learning.media.mit.edu/">About</a></li>
{% endblock %}

{% block banner %}
      <div class="hero-unit">
        <div class="container">
        <div class="row">
        <div class="span3">
        <img src="/static/images/festival-of-learning.png" width="150" height="150">
        </div>
        <div class="span11">
        <p>The Festival of Learning is a two-day festival on 27-28 January where anyone from E14 and E15 can teach, learn, and collaborate!
        Formats include one-on-one tutorials, clinics, discussion circles, workshops, playdates, games, collaborative construction projects and more.</p>
        <p><a href="/sessions/browse" class="btn primary large">Explore sessions ideas &raquo;</a></p>
        </div>
        </div>
        </div>
      </div>
{% endblock %}

templates/session/submit.html
{% extends 'session/base.html' %}

{% block pagetitle %}Submit Session{% endblock %}

{% block navbar %}
            <li><a href="/">Home</a></li>
            <li class="active"><a href="/sessions/submit">Submit Session</a></li>
            <li><a href="/sessions/browse">Browse Sessions</a></li>
            <li><a href="http://festival-of-learning.media.mit.edu/">About</a></li>
{% endblock %}

{% block scripts %}

    <script src="/static/js/bootstrap-twipsy.js"></script>
    <script src="/static/js/bootstrap-popover.js"></script>
    <script src="/static/js/bootstrap-modal.js"></script>
    <script src="/static/js/bootstrap-alerts.js"></script>
          <script>
            $(function () {
              $("a[rel=twipsy]").twipsy({
                live: true
              })
            })
          </script>

{% endblock %}


{% block banner %}
{% if success %}
{% else %}
<div class="alert-message notice fade in" data-alert="alert">
<a class="close" href="#">&times;</a>
<p><strong>Note:</strong> Submitting a session idea does not necessarily mean that you have to commit to conducting it. You can defer your decision till &lt;DATE&gt; </p>
</div>
{% endif %}
{% endblock %}

{% block primary %}

<div class="row">
 <div class="span15">

 {% if success %}
 <h3>Success</h3>
 <div class="alert-message block-message success fade in" data-alert="alert">
  <a class="close" href="#">×</a>
  <p><strong>Submission successful!</strong><br>Your session idea has been succesfully submitted.</p>
  <div class="alert-actions">
    <a class="btn small" href="/sessions/browse">Browse other session ideas</a> 
  </div>
</div>
 {% else %}

  <h3>Submit a session idea</h3>
    <form method="POST" action="/sessions/submit" enctype="multipart/form-data" class="form-stacked">{% csrf_token %}

    {% if form.non_field_errors %}
    <div class="alert-message error fade in" data-alert="alert">
    <a class="close" href="#">&times;</a>
    <p>{{ form.non_field_errors }}</p>
    </div>
    {% endif %}

     <fieldset>

          {% if form.title.errors %}
          <div class="clearfix error">
          {% else %}
          <div class="clearfix">   
          {% endif %}

            <label for="id_title">Title</label>
            <div class="input">
              <input class="xlarge" id="id_title" name="title" size="30" type="text" placeholder="Title of your proposed session">
              {% if form.title.errors %}
              <span class="help-block">
              {{form.title.errors}}
              </span>
              {% endif %}
            </div>
          </div><!-- /clearfix -->

          {% if form.description.errors %}
          <div class="clearfix error">
          {% else %}
          <div class="clearfix">
          {% endif %}
   
            <label for="id_description">Description</label>
            <div class="input">
              <textarea class="xxlarge" id="id_description" name="description" rows="5"></textarea>
              <span class="help-block">
              {% if form.description.errors %}
              {{form.description.errors}}
              {% else %}
                Short description of the session (HTML allowed).
              {% endif %}
              </span>
            </div>
          </div>

          {% if form.type.errors %}
          <div class="clearfix error">
          {% else %}
          <div class="clearfix">
          {% endif %}

            <label for="id_type">Type</label>
            <div class="input">
              <input class="xlarge" id="id_type" name="type" size="30" type="text" placeholder="Type/format of your session">
              {% if form.type.errors %}
              <span class="help-block">
              {{form.type.errors}}
              </span>
              {% else %}
              <span class="help-block">
              (e.g. one-on-one tutorials, clinics, discussion circles, workshops, playdates, games, collaborative construction projects, etc)
              </span>
              {% endif %}
            </div>
          </div><!-- /clearfix -->

          {% if form.duration.errors %}
          <div class="clearfix error">
          {% else %}
          <div class="clearfix">
          {% endif %}

            <label for="id_duration">Duration</label>
            <div class="input">
              <input class="xlarge" id="id_duration" name="duration" size="30" type="text" placeholder="Estimated duration of your session">
              {% if form.duration.errors %}
              <span class="help-block">
              {{form.duration.errors}}
              </span>
              {% else %}
              <span class="help-block">
              (e.g. 30 mins, 1 hour, 2 hours, all day)
              </span>
              {% endif %}
            </div>
          </div><!-- /clearfix -->
        
          <input type='hidden' name='facilitator' value='{{ user.id }}'> 
          <input type='hidden' name='status' value='unconfirmed'>

          <div class="actions">
            <input type="submit" class="btn primary" value="Submit">&nbsp;<button type="reset" class="btn">Cancel</button>
          </div>

     </fieldset>
    </form>

{% endif %}

 </div>
</div>

{% if success %}
{% else %}
<div class="row">
<div class="span15">
<div class="alert-message error fade in" data-alert="alert">
<a class="close" href="#">&times;</a>
<p><strong>Note:</strong> We have not implemented editing of submissions yet (<em>WIP</em>), so please double check your submissions before hitting the submit button.</p>
</div>
</div>
</div>
{% endif %}

{% endblock %}